name: CI & Release

on:
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build & Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      # Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & test frontend
        working-directory: frontend
        run: |
          npm ci
          npm run test -- --passWithNoTests
      - name: Build frontend production bundle
        working-directory: frontend
        run: npm run build

      # Python backend
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Python deps (if any)
        shell: bash
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      - name: Run Python tests (if any)
        shell: bash
        run: |
          pytest || true

  build-and-release:
    name: Build & Publish Installer
    runs-on: windows-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3

      # Build installer
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & build installer
        working-directory: installer
        run: npm ci && npm run build

      # Create or update GitHub Release Draft
      - name: Create or update Release draft
        id: ghr
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true

      - name: Upload installer asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.ghr.outputs.upload_url }}
          asset_path: installer/dist_installer/QMMS-Setup-${{ github.ref_name }}.exe
          asset_name: QMMS-Setup-${{ github.ref_name }}.exe
          asset_content_type: application/octet-stream
