name: CI & Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # — Node & frontend tests —
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & test frontend
        working-directory: frontend
        run: |
          npm ci
          npm test -- --passWithNoTests

      # — Python tests (shell: bash so we can use “[ -f ]”) —
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Python deps
        shell: bash
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      - name: Run Python tests
        shell: bash
        run: |
          pytest || true

  build-and-release:
    needs: build-and-test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # — Build your Windows installer in its own folder —
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & build installer
        working-directory: installer
        run: |
          npm ci
          npm run build

      # — Draft a GitHub Release named after the pushed tag —
      - name: Create GitHub Release (draft)
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true

      # — Upload the built .exe as a release asset —
      - name: Upload installer asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: installer/dist_installer/QMMS-Setup-${{ github.ref_name }}.exe
          asset_name: QMMS-Setup-${{ github.ref_name }}.exe
          asset_content_type: application/octet-stream
