name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & test frontend
        working-directory: frontend
        run: |
          npm ci
          npm run test -- --passWithNoTests

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python deps
        if: ${{ always() && (contains(github.event.head_commit.modified, 'requirements.txt') || contains(github.event.head_commit.added, 'requirements.txt')) }}
        run: |
          pip install -r requirements.txt

      - name: Run Python tests
        continue-on-error: true
        run: |
          pytest || true
