name: Full CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # 1) Lint every workflow file
  lint-workflows:
    name: 🔍 Lint CI YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint
      - name: Run yamllint
        run: yamllint .github/workflows/**/*.yml

  # 2) Build & Test each Node folder
  node-build:
    name: ⚙️ Build & Test ${{ matrix.folder }}
    runs-on: ubuntu-latest
    needs: lint-workflows
    strategy:
      matrix:
        folder: [ frontend, installer ]
    defaults:
      run:
        working-directory: ${{ matrix.folder }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build or Test
        run: |
          if [ "${{ matrix.folder }}" = "installer" ]; then
            npm run build
          else
            npm test -- --passWithNoTests || true
          fi

  # 3) Lint & Test Python (optional)
  python-lint-test:
    name: 🐍 Lint & Test Python
    runs-on: ubuntu-latest
    needs: node-build
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python deps
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Lint with flake8
        run: flake8 .

      - name: Run pytest (no-fail)
        run: pytest || true
