name: CI

on:
  push:
    branches:
      - main

jobs:
  build-installer-and-python:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: installer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & build installer
        run: |
          npm ci
          npm run build -- --config electron-builder.json

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python deps (if any)
        shell: bash
        run: |
          if [ -f ../requirements.txt ]; then
            pip install -r ../requirements.txt
          fi

      - name: Run Python tests
        shell: bash
        run: |
          pytest || true

