name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Install & test your React frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & test frontend
        working-directory: frontend
        run: |
          npm ci
          npm run test -- --passWithNoTests

      # 3) Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4) Install Python deps
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # 5) Run pytest (but don’t fail the whole job if there are no tests yet)
      - name: Run Python tests
        continue-on-error: true
        run: |
          pytest

