name: CI Pipeline

# Run on every push to main
on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      # 1. Check out the code
      - uses: actions/checkout@v3

      # 2. Set up Node.js 18
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install & test frontend (allow no-tests)
      - name: Install & test frontend
        working-directory: frontend
        run: |
          npm ci
          npm run test -- --passWithNoTests

      # 4. Set up Python 3.x
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 5. Install Python deps if requirements.txt exists
      - name: Install Python deps
        if: ${{ always() && (files.changed | contains('requirements.txt')) }}
        run: |
          pip install -r requirements.txt

      # 6. Run Python tests (allow no-tests)
      - name: Run Python tests
        continue-on-error: true
        run: |
          pytest || true
